# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.amazon.com/s?k=drills&s=salesrank")
    #self.driver.set_window_size(550, 692)
    #self.driver.find_element(By.ID, "glow-ingress-line1").click()
    #self.driver.find_element(By.ID, "glow-ingress-line1").click()
    #self.driver.find_element(By.ID, "GLUXChangePostalCodeLink").click()
    #self.driver.find_element(By.ID, "GLUXZipUpdateInput").send_keys("78722")
    #self.driver.find_element(By.CSS_SELECTOR, "#GLUXZipUpdate .a-button-input").click()
    #self.driver.find_element(By.ID, "a-autoid-5-announce").click()
    print(self.driver.page_source)


if __name__ == '__main__':
    test = TestTest1()
    test.setup_method(0)
    test.test_test1()

  
