CREATE TABLE "prices" (
	"website"	TEXT,
	"date"	INTEGER,
	"prod_id"	TEXT,
	"upc"	TEXT,
	"product"	TEXT,
	"manufacturer"	TEXT,
	"model"	TEXT,
	"price"	NUMERIC,
	"list_price"	NUMERIC,
	"in_stock"	INTEGER,
	"max_qty"	INTEGER,
	"seller"	TEXT,
	"listings"	INTEGER,
	"arrives"	TEXT,
	"weight"	INTEGER,
	"reviews"	INTEGER,
	"rating"	NUMERIC,
	"rank"	INTEGER
)